# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-01 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_another'),
    ]

    operations = [
        migrations.AddField(
            model_name='another',
            name='anotherfield',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
