# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-01 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_another_anotherfield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Another',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created',
        ),
    ]
